<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <Features>$(Features);runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sources\LearnAsync\LearnAsync.csproj" />
  </ItemGroup>

</Project>
